<a href="https://colab.research.google.com/github/anshpathak269-ops/booklist/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [23]:
a=list(range(0,7))
print(a)

[0, 1, 2, 3, 4, 5, 6]


In [22]:
a=list(range(0,8,2))
print(a)

[0, 2, 4, 6]


In [1]:
from re import X
list_1=[0,1,2,3]
list_2=[0,2,4,6]
lst = []
for i in range(0,len(list_1)):
  x = list_1[1]*list_2[i]
  lst.append(x)
  print("the product is",lst)

the product is [0]
the product is [0, 2]
the product is [0, 2, 4]
the product is [0, 2, 4, 6]


In [2]:
z=[0,1,2,3]
print(z*2)


[0, 1, 2, 3, 0, 1, 2, 3]


In [9]:
import numpy as np

x = np.array([2.1, 3.4, 5.1], dtype='int')
print(x)

[2 3 5]


In [ ]:
import numpy as np
a=np.array({1,2,3,4,5,'ashwi'})

In [10]:
import numpy as np

# 3x3 identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
q1=np.full((2,3),5)
print(q1,q1.shape)

[[5 5 5]
 [5 5 5]] (2, 3)


In [12]:
q1=np.eye(3)
print(q1,q1.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [13]:
q1=np.ones((2,3,4))
print(q1,q1.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] (2, 3, 4)


In [14]:
q1=np.eye(5,4,dtype='bool')
print(q1,q1.shape)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]
 [False False False False]] (5, 4)


In [15]:
q1=np.linspace(1000,5000,13)
print(q1)

[1000.         1333.33333333 1666.66666667 2000.         2333.33333333
 2666.66666667 3000.         3333.33333333 3666.66666667 4000.
 4333.33333333 4666.66666667 5000.        ]


In [19]:
import numpy as np

q1=np.arange(1,20,2)
print(q1,q1.shape)

[ 1  3  5  7  9 11 13 15 17 19] (10,)


In [20]:
import numpy as np
q1=np.random.randint(5,8,(6,4))
print(q1)

[[7 7 6 7]
 [7 6 6 6]
 [7 7 7 6]
 [6 7 5 7]
 [6 6 5 6]
 [6 7 7 7]]


In [21]:
import numpy as np
q1=np.random.randint(5,8,(6,4))
a=q1.shape
b=q1.size
c=q1.dtype
d=q1.ndim
print(a,b,c,d)
print(q1)

(6, 4) 24 int64 2
[[6 7 5 5]
 [7 6 7 6]
 [5 7 6 6]
 [5 7 5 5]
 [6 7 5 5]
 [6 6 6 7]]
